CREATE DATABASE PLATPET

USE PLATPET

CREATE TABLE PLANO(
	IDPLANO int IDENTITY(1,1) NOT NULL,
	TIPOPLANO int NOT NULL,
	DESCPLANO varchar(100) NOT NULL,
	DURAPLANO int NOT NULL,
	VALORPLANO numeric(10, 2) NOT NULL)

SELECT IDPLANO,TIPOPLANO,DESCPLANO,DURAPLANO,VALORPLANO FROM PLANO

INSERT INTO PLANO (TIPOPLANO,DESCPLANO,DURAPLANO,VALORPLANO) VALUES (1,'Plano de promoção anual',1,120)

DELETE FROM PLANO WHERE IDPLANO = 1

UPDATE PLANO SET TIPOPLANO = @A, DESCPLANO = @B, DURAPLANO =@C, VALORPLANO = @D WHERE IDPLANO = 1